server:
  port: 8000
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
zuul:
  routes:
    goods:
      path: /goods/**
      serviceId: goods
    order:
      path: /order/**
      serviceId: order
    user:
      path: /user/**
      serviceId: user
    common:
      path: /common/**
      serviceId: common